services:
  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
       - ./analytics:/home/jovyan/work/
    environment:
      - GRANT_SUDO=yesd
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python
  spark:
    build:
      context: ./notebook
      dockerfile: spark.Dockerfile
    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
  spark-worker:
    build:
      context: ./notebook
      dockerfile: spark.Dockerfile
    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=test
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
